name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    env:
      TESTING: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup Python Virtual Environment
        run: python -m venv python3-virtualenv

      - name: Install dependencies
        run: python3-virtualenv/bin/pip install -r requirements.txt

      - name: Run tests
        run: ./run_test.sh
